name: test-app-with-Jest
run-name: ${{ github.actor }} is testing the application
on: 
  push:
    branches:
      - development
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/delve
      JWT_SECRET: ${{secrets.JWT_SECRET}}
      PORT: 8000
      IO_PORT: 8001
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Clean install dependencies
        run: npm ci
      - name: Push schema to database
        run: npm run db:push
      - name: Seed database
        run: npm run db:seed
      - name: Run tests
        run: npm run test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Clean install dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Get directory layout
        run: dir
      - name: Copy schema to build folder
        run: cp /prisma/schema.prisma /dist/prisma
      - name: Copy configuration to build folder
        run: cp package.json /dist
      - run: cp package-lock.json /dist
      - name: Create artifact
        run: zip -r artifact.zip /dist
      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Delve app backend
          environment_name: delve-app-environment
          version_label: 0.1
          region: us-east-1
          deployment_package: artifact.zip
